# Generated by Django 2.1.15 on 2023-12-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=4)),
                ('planted_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-planted_on'],
            },
        ),
    ]
