# Generated by Django 2.1.15 on 2023-12-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_auto_20231203_0347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
    ]
