# Generated by Django 2.1.15 on 2023-12-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_auto_20231203_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('appearance', models.CharField(choices=[('SPOT', 'Spotted'), ('YELLOW', 'Yellowing'), ('WILT', 'Wilting'), ('HEALTHY', 'Healthy')], default='HEALTHY', max_length=7)),
                ('leaf_age', models.CharField(choices=[('YOUNG', 'Young'), ('MATURE', 'Mature'), ('OLD', 'Old')], default='MATURE', max_length=6)),
            ],
        ),
    ]
