# Generated by Django 2.1.15 on 2023-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_auto_20231206_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='planted_on',
            field=models.TextField(default='20/20/20', max_length=200),
        ),
    ]
