# Generated by Django 2.1.15 on 2023-12-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_crop_planted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='planted_on',
        ),
    ]
